### ISSUE TITLE
Monitoring - iPerf

### ISSUE THREAD

**Issue by V3nic** [PenguinCloud/WaddlePerf#8]

**Comment by ArcherPTG** [comment]
on todo, list just need to be polished

**Comment by ArcherPTG** [comment]
moved to backlog, shifting focous on other projects for priority

**Comment by PenguinzPlays** [comment]
Missing an nginx front end , and need to figure out authentication... appears broken. Check the issues assigned to the project for more work to be accomplished.

**Comment by ArcherPTG** [comment]
Working on iPerf:
Cleaned up the Build Files
Working on getting the WebUI working for it
Researching the other items needed for the project

**Comment by ArcherPTG** [comment]
Still no confirmation on the Webui from KP
Working on the other items in the list for the project

**Comment by ArcherPTG** [comment]
venic contniuin work on iperf,

**Comment by ArcherPTG** [comment]
Worked on trying to get the UI working for iPerf.

**Comment by ArcherPTG** [comment]
Met with KP.... I wasn't meant to be doing the Django UI side of things, lol! But at least it's installing for the UI

**Comment by ArcherPTG** [comment]
working clstering, issues with nginx,
invalid host and upstream for config file,

**Comment by ArcherPTG** [comment]
looking into ngnx errors, 
trying out code sent to testresult, keep geting "port is duplicte " error/bug

**Comment by ArcherPTG** [comment]
issues with ngnix image being denied

**Comment by ArcherPTG** [comment]
continuing work on this for now, haivng issues with pullingimages for other projects, keep getting denied

**Comment by PenguinzPlays** [comment]
> continuing work on this for now, haivng issues with pullingimages for other projects, keep getting denied

Have to have developer permissions on the project to pull them.

**Comment by PenguinzPlays** [comment]
> 



> looking into ngnx errors, trying out code sent to testresult, keep geting "port is duplicte " error/bug

This is likely because we already run the python3 simple web server on port 80, which is the default port for nginx as well. Would need to remove the part which is starting the python3 simple web server first (which is fine to do btw).

**Comment by ArcherPTG** [comment]
working on clustring,
